server:
    port: 8080

logging:
    level:
        org:
            springframework:
                security: info

spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: ${CLIENT_ID}
                        client-secret: ${CLIENT_SECRET}
    datasource:
        password: ${DB_PASSWORD}
        username: ${DB_USER}
        url: jdbc:postgresql://localhost:5432/postgres

exambyte:
    rollen:
        admin: jubus108
