logging:
    level:
        org:
            springframework:
                security: info

spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: ${CLIENT_ID}
                        client-secret: ${CLIENT_SECRET}

exambyte:
    rollen:
        admin: jubus108
        tutor: jubus108
